### ISSUE TITLE
Ledger.Exposed/XRP Rich List is no longer available

### ISSUE THREAD

**Issue by ColdBio** [yyolk/awesome-xrpl#13]
## Issue
Unfortunately Ledger Exposed is no longer available and will need to be removed from the XRPL Explorer section. 

## Screenshot from the Ledger.Exposed Previously: the XRPL Rich List site
![Screenshot 2022-02-20 at 14 41 45](https://user-images.githubusercontent.com/64978825/154848126-1afb4f42-a030-4f55-ae5b-b13a273ccdd0.png)

**Comment by wojake** [comment]
Thank you and I'll remove it, do you have any other reliable service that you think is suitable as a replacement?

**Comment by wojake** [comment]
Thank you for your contribution
